project:
  type: website

website:
  title: "iSEE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Learn
      - text: Gallery
        menu:
        - panels.qmd
        - apps.qmd
      - href: dashboard.qmd
        text: Status
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
