project:
  type: website

# Icons in navbar come from: https://icons.getbootstrap.com/
website:
  title: "iSEE"
  google-analytics: "G-D858FLKVB5"
  description: "Nexus of information for the Bioconductor package iSEE, its extensions, and its learning resources."
  site-url: "https://isee.github.io/"
  repo-url: "https://github.com/iSEE/isee.github.io/"
  repo-actions: [edit, issue]
  repo-branch: main
  navbar:
    left:
      - href: install.qmd
        icon: download
        text: Install
      - href: resources.qmd
        icon: mortarboard
        text: Learn
      - text: Gallery
        icon: collection
        menu:
        - href: panels.qmd
          icon: code-square
        - href: apps.qmd
          icon: window
      - href: dashboard.qmd
        icon: speedometer
        text: Status
      - href: about.qmd
        icon: info-circle
        text: About

format:
  html:
    site-url: https://isee.github.io
    theme: cosmo
    css: styles.css
    toc: true
    #link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
