---
title: "Installation"
---

## Install {{< fa brands r-project >}}

*iSEE* requires Bioconductor 3.7+ which in turn requires R 3.5+.
Choose a version of R that matches your computer’s operating system.
We recommend using the latest version of R to access the latest version of *iSEE*.

[{{< fa download >}} Download and install R](https://cran.rstudio.com/)

## Install iSEE

We recommend installing the latest stable version of *iSEE* from the Bioconductor repository.

[{{< fa download >}} Install iSEE from Bioconductor](https://bioconductor.org/packages/iSEE/)

::: {.callout-note}
Follow the link above and scroll down to the section *Installation*.
:::

## Install the iSEE-verse

Most users do not need the full collection of packages that provide extensions to *iSEE*.

For the aficionados, the command below does just that; it combines all the known *iSEE* extension packages into a single command that installs them all in one go.

Great for copy-pasting, and for our [{{< fa gauge-high >}} download statistics](https://bioconductor.org/packages/stats/bioc/iSEE/)!

::: {.callout-note}
The code below assumes you have already installed the package [*BiocManager*](https://CRAN.R-project.org/package=BiocManager), which will be the case if you have already installed *iSEE* or any other package from the Bioconductor repository.
:::

```{r, eval=FALSE}
BiocManager::install(c(
    "iSEEde",
    "iSEEhex",
    "iSEEhub",
    "iSEEindex",
    "iSEEpathways",
    "iSEEtree",
    "iSEEu"
))
```
