# Resources

## GitHub organisation

The link below redirects to the GitHub organisation that stores the source code for packages maintained by the core developers, as well as additional resources such as tutorials and workshops.

<https://github.com/iSEE>

## Bioconductor pages

The links below redirect to the web page for each package on the Bioconductor website.

Each page contains information and links to further resources for the latest version of each package available from Bioconductor.

::: {.callout-note}
The links below redirect either to the latest version of each package on the *release* branch if available,
or the latest version on the *development* branch for recent package that have are not distributed on a *release* branch yet.
For more information, see [Using Bioconductor](https://www.bioconductor.org/install/).
:::

- <https://bioconductor.org/packages/iSEE/>
- <https://bioconductor.org/packages/iSEEde/>
- <https://bioconductor.org/packages/iSEEhex/>
- <https://bioconductor.org/packages/iSEEhub/>
- <https://bioconductor.org/packages/iSEEindex/>
- <https://bioconductor.org/packages/iSEEpathways/>
- <https://bioconductor.org/packages/iSEEu/>

## Online documentation (pkgdown)

The links below redirect to help pages and vignettes for the latest version of each package pushed to GitHub.

::: {.callout-note}
The latest version pushed to GitHub  may be *ahead* of the latest version available on Bioconductor.
:::

- <https://isee.github.io/iSEE>
- <https://isee.github.io/iSEEde/>
- <https://isee.github.io/iSEEhex/>
- <https://isee.github.io/iSEEhub/>
- <https://isee.github.io/iSEEindex/>
- <https://isee.github.io/iSEEpathways/>
- <https://isee.github.io/iSEEu/>

## Workshops

### European Bioconductor Conference 2023

- **Materials:** <https://isee.github.io/iSEEDemoEuroBioC2023/articles/iSEEdemo.html>

### European Bioconductor Conference 2020

- **Materials:** <https://isee.github.io/iSEEWorkshopEuroBioc2020/>
- **Slides:** <https://isee.github.io/iSEEWorkshopEuroBioc2020Slides/>

### Bioconductor Conference 2020 Workshop

- **Materials:** <https://isee.github.io/iSEEWorkshop2020/>
- **Slides:** <https://isee.github.io/iSEEWorkshop2020Slides/>

### Bioconductor Conference 2019 Workshop

- **Materials:** <https://isee.github.io/iSEEWorkshop2019/>
- **Slides:** <https://isee.github.io/iSEEWorkshop2019Slides/>

## Books

### Extending iSEE

This book describes how to use the *iSEE* application programming interface (API) to develop new panel types for custom visualizations.
The book also presents case studies to illustrate the development process for a variety of custom panels.

<https://isee.github.io/iSEE-book/>

### iSEETheBook

This new book (work in progress) aims to compile essential knowledge about iSEE, catering for three main groups of users:

- End users interacting with the graphical user interface in their web browser.
- Developers of scripted web-applications using iSEE to showcase data sets.
- Developers of extensions contributing new functionality and packages to the iSEE ecosystem.

<https://isee.github.io/iSEETheBook/>

## Videos

Our YouTube channel includes videos documenting and demonstrating iSEE apps in action.

<https://www.youtube.com/@iSEEdevelopers>

{{< video https://www.youtube.com/embed/R72Tbb5vxmw >}}

<!-- 
Other resources:

- <https://github.com/iSEE/iSEE_instances>
-->